### ISSUE TITLE
Logo not rendering

### ISSUE THREAD

**Issue by sasmitaditya13** [IMGIITRoorkee/Easysell-website#10]
**Describe the bug**
Logo of the site is not rendering.

**Expected behavior**
Logo should be rendered correctly.

**Screenshots**
Current:
![Screenshot_20241214_192329](https://github.com/user-attachments/assets/4ded8f41-e0d0-4246-94dc-cc8c3433a299)
![Screenshot_20241214_192436](https://github.com/user-attachments/assets/8d1c0a60-445a-4bbc-920e-d1d66843c933)

**Comment by Sanat-Jha** [comment]
@sasmitaditya13 Issue already fixed in PR #31
