### ISSUE TITLE
Add a "Go To Top Button" for better navigation.

### ISSUE THREAD

**Issue by Akshat1276** [IMGIITRoorkee/Easysell-website#48]
**Is your feature request related to a problem? Please describe.**
When we are near the bottom of the site and want to go to the top, it is quite irritating to scroll up to reach the top.

**Describe the solution you'd like**
I'd like to add a button near the bottom right corner, which when active, will take us to the top of the page.

**Comment by Akshat1276** [comment]
Good Afternoon
Kindly approve this issue and add difficulty tag, so that I can start working on it.
Thank You

**Comment by sasmitaditya13** [comment]
Get your design approved by @nitininhouse and then start working om it.

**Comment by nitininhouse** [comment]
@Akshat1276   Keep it mind to match the button's style (colors, fonts) with the website theme in order to maintain consistency.

**Comment by Akshat1276** [comment]
@nitininhouse Sir is this design okay?
![image](https://github.com/user-attachments/assets/df06943f-c3b3-40f4-b54a-8b700a70a701)

**Comment by nitininhouse** [comment]
Instead of writing 'UP,' use an upward arrow symbol (⬆) to make it more intuitive and visually appealing.
